### ISSUE TITLE
Parens in decltype(int) have unexpected tokenization

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#100]
I would expect that the tokenization would end with the punctuation name:

![image](https://user-images.githubusercontent.com/38270282/56220914-90e0e080-6069-11e9-8c2c-be803cd792c2.png)

**Comment by jeff-hykin** [comment]
I see, this was intentional, but I believe I misinterpreted the following issues as wanting the parentheses to be part of the match. 
https://github.com/Microsoft/vscode-cpptools/issues/938
https://github.com/atom/language-c/issues/246

We'll remove both `keyword.operator.functionlike.cpp` and `storage.type.decltype.cpp` from the ()'s

**Comment by matter123** [comment]
Fixed in 1.8.2

**Comment by alexr00** [comment]
Looks good, thank you!
