### ISSUE TITLE
In `using namespace std` std could be entity.name.type.namespace.cpp

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#101]
Currently it is entity.name.namespace.cpp. In the old grammar it was entity.name.type.cpp.

This would be very helpful for the existing VS Code themes! If this isn't a good rename, then I'll need to special case some of theme rules. Not ideal, but possible.

**Comment by matter123** [comment]
Language  | Scope
--------------|--------
Typescript | `entity.name.type.module.ts`
C# | `entity.name.type.namespace.cs`
java | `storage.modifier.import.java`
rust | `source.rust`
coffeescript | `entity.name.function.coffee`
groozy | `storage.modifier.package.groovy`
ruby | `entity.name.type.module.ruby`

It seems like `entity.name.type.namespace is an appropriate name.

**Comment by matter123** [comment]
Fixed in 1.8.2

**Comment by jeff-hykin** [comment]
Sorry that this change wasn't in the Log, it should've been, it was done awhile ago.

I have implemented and pushed the changes, but I would debate that `entity.name.namespace` should be used.

In `String thing;`the `String` would be `entity.name.type`
All of these patterns follow this idea:
`entity.name.type.enum`
`entity.name.type.union`
`entity.name.type.struct`
`entity.name.type.class`
`entity.name.type.inherited`
`entity.name.type.template`

However some things are entities, but they are not types
`entity.name.function`
`entity.name.operator`
Ideally macros would be `entity.name.macro` although they are currently `entity.name.function.preprocessor`

Since `namespace` is not a type, e.g. `ANamespace value;` would not work, I don't think it should be labeled with `type`. This is because themes likely want to color user-defined types (`entity.name.type`)  and built-in types `storage.type.primitive` as the same color, but having `entity.name.type.namespace` would then be an edgecase that they would have to additionally add `entity.name.type.namespace` to force it to be the color that is used for `entity.name` without `type`.

**Comment by matter123** [comment]
While I don't disagree that namespaces are not types. Functions are types
[[dcl.fct]/3](http://eel.is/c++draft/dcl.fct#3)
> A type of either form is a function type.

and (non-normative) (emphasis mine)
[[basic.types]/1](http://eel.is/c++draft/basic.types#1)
> [ Note: [basic.types] and the subclauses thereof impose requirements on implementations regarding the representation of types.
There are two kinds of types: fundamental types and compound types.
Types describe objects, references, or **functions.**
— end note]

**Comment by jeff-hykin** [comment]
It doesn't seems like either of those claim that functions themselves are types. "Types describe ... functions" doesn't really say "functions are types".

**Comment by matter123** [comment]
what other meaning is there for "function type"?

**Comment by jeff-hykin** [comment]
From what I understand functions have types: a combination of their return types and parameters, but functions themselves are not types.

You can't declare `AFunctionName a_variable;`

**Comment by matter123** [comment]
Ok yead re-reading that seems more correct
Additionally: https://godbolt.org/z/C6nDq0
> \<source\>:11:10: note:   expected a type, got 'foo'

**Comment by jeff-hykin** [comment]
Went ahead and made this change with `v1.9.1`
`entity.name.type.namespace` => `entity.name.namespace`

There are a decent number of tag changes with v1.9.0 but none of them seem to affect the VS Code default theme.
