### ISSUE TITLE
Inheritance access specifier not colorized at linebreak

### ISSUE THREAD

**Issue by ember91** [jeff-hykin/cpp-textmate-grammar#14]
**Describe the bug**
- OS and Version: Ubuntu 18.04.2 LTS
- VS Code Version: 1.31.1
- Better C++ Syntax Extension Version: 1.4.11
- Other extensions you installed (and if the issue persists after disabling them): C/C++. The issue persists after disabling it.
- A clear and concise description of what the bug is: When linebreaking after an inheritance colon, the access specifier, such as 'public', is not colorized.

**To Reproduce**
1. Create a new file with extension '.cpp'.
2. Input the code below in the newly created file. Note the linebreak after the colon.
```
class B
{};

class A : 
  public B
{};
```
3. Try removing the linebreak, writing 'public B' on the same line as 'class A'. The keyword is suddenly colorized.

**Expected behavior**
The 'public' keyword should be colorized regardless if there is a linebreak or not. 

**Screenshots**
![screenshot from 2019-03-08 15-36-37](https://user-images.githubusercontent.com/31469580/54035423-9ec55b00-41b9-11e9-832d-b37ba38758c9.png)

**Additional context**
This issue exists with default VS code highlighting as well.

**Comment by jeff-hykin** [comment]
Just for reference (for other people) fixing this issue also would fix the issue posted here https://github.com/atom/language-c/issues/245 

I've got bad news though :/

TextMate grammars have basically two ways of matching things
1. Regex match
2. Range (start and end) match
- Start must be a Regex match
- End must be a Regex match

The caveat is, the Regex match for TextMate cannot match newlines. (This is something inherently limiting about the TextMate implementation.) If something contains newlines, say a class definition, then you're supposed to use a Range. 

Right now the range start is basically `class {` and the range end is `}`, but since there's no way to include newlines in the start, theres no straightforward way to match the `class : \n*parents* {` at the start. We could remove the  `class {`, `}` range, but it is also used to style things like `public:`, and `private:` which are only allowed in class/struct definitions.

Now, their might be a clever way to get a make-shift solution and get around this which I'll try to work on, but the root problem is that the syntax highlighting is inherently limited. This is something a Tree Sitter would fix and this issue should additionally be logged on the VS Code repo.

**Comment by ember91** [comment]
Thanks for the response! Perhaps waiting for tree sitter is the right way to go. It seems like it may appear in VS code in the future. I'll report the issue there as well, which may speed up the process.

**Comment by ember91** [comment]
The issue has already been reported in VS code [here](https://github.com/Microsoft/vscode/issues/30073), which moved [here](https://github.com/atom/language-c/issues/245), as previously mentioned by [Jeff](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/14#issuecomment-470963402).

**Comment by jeff-hykin** [comment]
Good news. I've been refactoring the code the last few days and I discovered a way to do it. 

It turns out the legacy code is not actually using a range, they're instead just using a very long normal pattern matcher for only the beginning of the class.

It is still going to take a bit to implement the fix, but at least it's possible. 👍

**Comment by jeff-hykin** [comment]
I published a fix this with version `1.6.1` and pushed it just now. I'm going to do more work on it since the whole class pattern/tagging needs to be updated, but for usage purposes it should at least be highlighted now!
