### ISSUE TITLE
about `<` and `>`

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#208]
At last vsc knew what `>>` is !! 
but,
![image](https://user-images.githubusercontent.com/10380828/58397696-b3144800-8084-11e9-8b65-ffbae3172b1d.png)

I just make it more readable.
https://github.com/lhmouse/asteria/blob/bafd08ea05a36ae3967a761396875f7a3b602fe3/asteria/src/rocket/cow_hashmap.hpp#L30

**Comment by peaceshi** [comment]
![image](https://user-images.githubusercontent.com/10380828/58398094-544fce00-8086-11e9-80e5-cdd4c9db6373.png)
and what it is the `.cpp`?

**Comment by jeff-hykin** [comment]
The `.cpp` is def a bug, means we probably need to add an empty-string check somewhere.

**Comment by jeff-hykin** [comment]
Just to give a little context to this problem.
If we use a Pattern, we can do pretty complex stuff, but its limited to one line (so doesn't work for <>)
If we use a Range (start + end), we can do multiline, however once the 'start' has matched, it will not stop until it matches an 'end'.

Meaning if we did the easy solution of start `<` end `>` then a less-than comparison would mess everything up because it would be looking for an end that doesn't exist.

Thats not to say this isn't solvable, its just not going to be a straightforward solution.

**Comment by peaceshi** [comment]
> Meaning if we did the easy solution of start `<` end `>` then a less-than comparison would mess everything up because it would be looking for an end that doesn't exist.
> 
> Thats not to say this isn't solvable, its just not going to be a straightforward solution.

the two ways is not enough both.
the impact ..... a little bit, but not much.
the person who want to write that should know what the mean is .
no highlight of the`<` `>` in templates maybe the best way for now.

and,
vsc should not use this parser engine. really a rubbish. they need to make a new. XD

**Comment by jeff-hykin** [comment]
Well @peaceshi I've actually been working with some other guys on getting the Tree sitter parser working in VS Code. 

This isssue a good example of where the tree-sitter would do a lot better.

With that said though the tree sitter is a long way off from being complete. It's running (you can download the extension) but the themes are all messed up.

**Comment by jeff-hykin** [comment]
> The `.cpp` is def a bug, means we probably need to add an empty-string check somewhere.

I found where this was coming from and fixed the issue. The `<>` is still an issue though

**Comment by jeff-hykin** [comment]
closing in favor of #246
