### ISSUE TITLE
source.cpp scope added twice

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#221]
In version 1.11.3, I'm seeing the `source.cpp` scope added twice for every token. It should be pretty easy to reproduce since it's happening on every token that I've checked so far!

**Comment by matter123** [comment]
This is as designed to ensure that `source.cpp` is present when c++ is embedded in markdown or similar..

**Comment by jeff-hykin** [comment]
Thanks for pointing this out. @matter123 is correct though, this change was made intentionally so that TextMate scopes could be language specific. This issue was waiting for the Objective-C/C++ fix before it could be implemented.

For example, lets say you want C++ keywords to be different from Haskell keywords.
`source.cpp keyword`  selects only C++ keywords
Before the update, that selector would only work in C++ files, if you opened a markdown file and wrote C++ code the styles wouldn't be applied. By adding the additional `source.cpp` it now works inside of markdown files.

If you think there is a better solution we'll change it though. The name can be changed to distinguish it, and ideally most TM grammar's would do something similar to allow better language specific theming.

**Comment by jeff-hykin** [comment]
I'm going to close this, but let me know if you think it should be reopened.

**Comment by alexr00** [comment]
Thanks for the explanation. I don't have a better/alternative suggestion!
