### ISSUE TITLE
Which color theme should I use to benefit from your syntax highlighting?

### ISSUE THREAD

**Issue by adam-kral** [jeff-hykin/cpp-textmate-grammar#229]
In your readme you say "your theme will be able to color your code better."
"Just install the VS Code extension and the changes will automatically be applied to all relevent files."

I see some color themes don't highlight much (Visual Studio Light), even with your extension. 

Personally I wanted to syntax highlight _data members_ (usages and definitions) to at-sight distinguish them from function declarations in header files and local variable usages in cpp files.

I think people would appreciate if the README featured a recommendation of one light and one dark theme which visualize most of the highlighting. (I don't even know which theme is in the screenshot examples.)

**Comment by matter123** [comment]
Unfortunately, due to the way textmate grammars work, The grammar has no way of distinguishing data members from local variables. Files are parsed line by line with very little context shared.

The theme in the example is [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme).  
I personally prefer [Horizon Theme](https://horizontheme.com/)  
[Two Monokai](https://github.com/alekseyt/vscode-two-monokai) is a C++ centric theme (you currently need to make the vsix yourself.)  
I Don't have any particular reccomendations for a light theme. @jeff-hykin ?

**Comment by jeff-hykin** [comment]
Hey @adam-kral, I think thats a good idea to mention themes that can take advantage of the additional tags. I can recommend [XD Theme ](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.xd-theme) to show off most all of the current features since that's the theme I maintain/use. The material theme is a good place to start if you're looking for something that has more colors than the stock themes.

As @matter123 said, sadly theres no way to distinguish variable-members from local variables, unless you're using the `.member` or `this->member` syntax.
However, you can distinguish them from from function declarations, and most themes should color function declarations differently by default.

Over the next few days I'll look up some themes that take advantage of the scopes and I'll add them to the readme.

**Comment by matter123** [comment]
Closing as the readme now contains suggestions on themes including two light themes (Winteriscoming and noctis).
