### ISSUE TITLE
s in sizeof not highlighted correctly in this macro

### ISSUE THREAD

**Issue by tristan957** [jeff-hykin/cpp-textmate-grammar#238]
```c
#define G_STATIC_ASSERT_EXPR(expr) ((void) sizeof (char[(expr) ? 1 : -1]))
```

language: C

**Comment by matter123** [comment]
I can't reproduce are you using 1.11.15?
![Screenshot from 2019-06-10 20-53-21](https://user-images.githubusercontent.com/714007/59242804-e1843e00-8bc1-11e9-8bc4-d434625272b5.png)

**Comment by matter123** [comment]
@tristan957 @peaceshi

As I can't reproduce I'm not entirely sure what the issue is. However, I suspect it's treating `izeof` as a function. To that end, the branch `Fix/#238` ensures that a function definition cannot be in the middle of an identifier. It would be appreciated if you could test the fix. To do that put the [generated file](https://raw.githubusercontent.com/jeff-hykin/cpp-textmate-grammar/Fix/%23238/syntaxes/c.tmLanguage.json) in `<vscode extension dir>/jeff-hykin.better-cpp-syntax-1.11.5/syntaxes` replacing the existsing c.tmLanguage.json.

**Comment by jeff-hykin** [comment]
I can't reproduce this either

**Comment by tristan957** [comment]
Let me look at the file again. To confirm I am on 1.11.5

**Comment by tristan957** [comment]
I am inspecting the textmate scopes. izeof is being a function. Language is actually C++ (symptom of .h files being C++, my bad)

**Comment by tristan957** [comment]
I can confirm the fix works. It also needs to be added to the C++ grammar

**Comment by tristan957** [comment]
I checked the old grammars again. The C grammar seems to handle this fine. The C++ grammar is the one that messes up

**Comment by matter123** [comment]
Yeah

**Comment by tristan957** [comment]
My apologies on mis-reporting the issue

**Comment by tristan957** [comment]
For your convenience, I have started a new project at https://github.com/tristan957/harvest-almanac as a new C-based project similar to tllt-cp in the event you want to run your textmate script on another project @matter123.
