### ISSUE TITLE
Two open angle brackets in template argument list disables syntax highlighting for rest of file.

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#35]
If a template has two 2 `<` (including the one after `template` than most syntax highlighting is disabled for the rest of the file.

![Screenshot from 2019-03-16 11-50-27](https://user-images.githubusercontent.com/714007/54480236-368efe80-47e3-11e9-90e7-59e216e90b38.png)

The rest of the file has the TM scope of `template.definition`. It looks like the issue first appeared in 1.4.0 ( 1.3.3 does not exhibit this issue).

For debugging
```
namespace test {
	template <class T>
	struct test {
		template <class U = std::vector<int>>
		bool operator()(U k) {}
	};
	struct test2 {
		bool operator()() = delete;
	};
} // namespace test

// no syntax highlighting
class test2 {};
```

**Comment by jeff-hykin** [comment]
Sadly the following code is also valid (and fails to highlight correctly).
```
template<typename RETURN_TYPE, int N = 0 > 1, typename Callable>
```
Which means matching the closing > is going to be nearly impossible.
I'll probably push a workaround fix for this, but it will be shallow/breakable

**Comment by jeff-hykin** [comment]
Alright I created a decent fix for most cases: 

<img width="996" alt="Screen Shot 2019-03-16 at 9 05 32 PM" src="https://user-images.githubusercontent.com/17692058/54484195-49c7bb80-482f-11e9-9962-57213589aafd.png">

I'm going to mark this as closed since that last case has more to do with support for #33 
I don't if #33 is fixable, but if it is then it will fully fix this issue.
