### ISSUE TITLE
wrong highlighting when initializing vector with size in ()

### ISSUE THREAD

**Issue by sykoram** [jeff-hykin/cpp-textmate-grammar#36]
`vector <int> v_name (3);`
v_name is highlighted as function

**Comment by matter123** [comment]
This is probably nearly impossible.

In general in C++ the expression `A B(C)` is impossible to disambiguate without actually compiling. If `C` is a type, the expression declares a function `B` taking `C`, returning `A`. If `C` is a non-type, than the expression declares a variable of type `A` named `B` constructed from `C`. Inside a function, it might be possible to recognize that a type proceeds `v_name` and that `v_name` could not be `entity.name.function.call`, But in a namespace, class, or global scope it is not generally possible. It might be possible that if one of the arguments cannot possibly be a type than it could be marked as a variable, however, that leads to inconsistency where `T *test(nullptr)` and `T *test(NULL)` are marked differently.

**Comment by jeff-hykin** [comment]
There's might be room for improvement, but sadly I think @matter123 is correct. In general this type of statement, its impossible to know whether it is declaring a function, or creating an instance.

There might be some hints that can be used to know, and I'll leave this open while investigating possible improvements.

**Comment by jeff-hykin** [comment]
I'm going to go ahead in close this. The only improvements we can really make are to add support for vector initializers as part of adding support for std, and there's already an issue for that.

**Comment by adam-kral** [comment]
I don't know which context this issue had, but I couldn't help to notice that when the extension is disabled, syntax highlighting (tried with Light+ theme for example) somehow _can_ differentiate between function declaration and variable construction. 

So construction of a local variable (blue) is not marked the same as calling a function (beige).

Again for now I have little knowledge about syntax highlighting in vscode but I see the extension is using the same tools (textmate grammar) as the extension building upon it, does it?

**Comment by matter123** [comment]
Can you provide an example snippet and vscode version?

**Comment by adam-kral** [comment]
I have 1.31.1, Light+ 

`struct A {
    A(int){};
};

void function() {}

int main() {
    A variable(1);

    function();
}`

![Screenshot 2019-06-08 at 21 57 24](https://user-images.githubusercontent.com/20720495/59151746-dc47b780-8a38-11e9-83d5-bf4c01e6f219.png)

But on cmd+hover there is some inconsistency:
![Screenshot 2019-06-08 at 21 57 02](https://user-images.githubusercontent.com/20720495/59151747-dc47b780-8a38-11e9-9c6e-c6fccdb468bc.png)

**Comment by matter123** [comment]
So it looks like the pattern that does that is https://github.com/jeff-hykin/cpp-textmate-grammar/blob/c66f3888743f8f5987c67c0c44181a055aaa1bba/source/languages/c/generate.rb#L574 I'm not sure why it disappeared when the grammars were split (@jeff-hykin ?), but its likely that it could be temporarily added back in while #71 is still in the works.

This issue isn't marked as nearly impossible because of this, however. Outside of a function scope, its usually impossible to distinguish a variable initialization from a function definition without compiling. This is why the grammar marks, and will probably continue to mark such declarations as a function definition.

It may be possible to recognize that the first argument is an expression that must be a type of must be a value and mark the declaration as a function definition or a variable declaration accordingly, but that could lead to some inconsistencies, e.g:
```c++
vector<int> a(5);
vector<int>b(some_constant);
```
would be marked differently.

**Comment by jeff-hykin** [comment]
I think it caused issues with some of the other patterns, but I can't say for certain since it was so long ago. Once we have strict contexts though we can add an initialization pattern, and on doing so we can probably also fix the vector<vector<>> issue.
