### ISSUE TITLE
C/C++ Themes

### ISSUE THREAD

**Issue by Colengms** [jeff-hykin/cpp-textmate-grammar#388]
Hi @jeff-hykin .  Posting this here, as I don't have an email address for you.  :)  We (vscode-cpptools @ MS) noticed the list of themes in README.md, and were wondering if we could get our themes added to the list?  We created [a C/C++ Themes extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-themes) to include colors for scopes of semantic tokens.  Without a theme to color them, our semantic colorization feature doesn't do much.  :/

Our themes actually do not include more colorization for syntactic tokens than the default VS Light/Dark themes in VS Code.  And, coverage of semantic tokens is limited, as the VS themes they are based on only colored a few of them.  We plan to add themes that align with the new Light/Dark themes in VS 2019, which color some additional tokens.  We are waiting until these themes are released (as they are currently only in Preview builds), and for customers to weigh in with feedback, before porting them.

Perhaps we could collaborate on a VS Code theme for C/C++ with good coverage of both syntactic and semantic scopes?

**Comment by jeff-hykin** [comment]
Sure! I'd be happy to collaborate. My email is `jeff.hykin@gmail.com` if you ever want to get in contact. I went ahead and added the theme to the list. I actually think it would be good to get the additional scopes into the pre-installed Dark+ theme since its designed to be the more advanced highlighter, and it doesn't really make sense to have a theme thats designed for only one language.

I bet @alexr00 can help with coordinating changes with the Dark+ Theme

Dark+
![dark+](https://user-images.githubusercontent.com/17692058/64701785-0b722880-d46f-11e9-876e-7984bb481e73.png)

Dark C++
![dark C++](https://user-images.githubusercontent.com/17692058/64701939-4a07e300-d46f-11e9-8146-1f39da2173af.png)

Side by side
![Screen Shot 2019-09-11 at 8 37 33 AM](https://user-images.githubusercontent.com/17692058/64702133-9b17d700-d46f-11e9-91a2-58bd00ff9e45.png)

Currently the Dark+ actually seems to highlight more than the Dark C++ theme, which is why I'd suggest adding scopes to it for consistency.

**Comment by jeff-hykin** [comment]
I'm going to go ahead to close this issue, but feel free to continue the conversation

**Comment by alexr00** [comment]
@Colengms let's take this over to https://github.com/microsoft/vscode/issues/80783. I'm amenable to adding more scopes to the Dark+ and Light+ themes,.
