### ISSUE TITLE
Couldn't highlight the word use '\c'  in Doxygen comments

### ISSUE THREAD

**Issue by Gorgeous2017** [jeff-hykin/cpp-textmate-grammar#449]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [x] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```
/**
 * @brief performs a "foo" action
 * @param a the action to preform
 *  @arg ACTION_1 action 1 to preform
 *  @arg ACTION_2 action 2 to preform
 * @retval ERROR_SUCCESS action performed successfully
 * @retval EPERM permission error
 * @note if \c a is zero, something \b bad happens
 */
int foo(int a);
```

## It looks like:

![Snipaste_2020-02-12_12-47-41](https://user-images.githubusercontent.com/33201519/74304339-a2813a80-4d97-11ea-9ec6-21266ca9d885.jpg)

 theme is One Dark Pro

## It should look like:
The word 'a' after @note couldn't highlight normally. In #354 PR, 'a' should be highlight.

**Comment by matter123** [comment]
This is an issue with your color theme.

You can use the vscode setting `editor.tokenColorCustomizations` to change the coloring for the tokens.
For more information on how to do this see #7 or the [visual studio code docs](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme).

Alternatively, if you feel that this behavior should be fixed by default, you may wish to file an issue with your color-theme.
