### ISSUE TITLE
extension not working for wsl ubuntu 20.04

### ISSUE THREAD

**Issue by RohitRanjangit** [jeff-hykin/cpp-textmate-grammar#482]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [x] This bug exists for C
- [x] This bug exists for C++
- [x] This bug exists for Objective-C
- [x] This bug exists for Objective-C++

## The code with a problem is:
```
void test_case(ll T){
    ll n;
    cin >> n;
    map<ll,ll> ai;
    loop(i,n){
        ll temp;
        cin >> temp;
        ai[temp] = i;
    }
    
}
```

## It looks like:
** screenshot + theme name preferable **
Theme: default dark+

![Screenshot (1)](https://user-images.githubusercontent.com/47271616/84116095-d2420580-aa4c-11ea-9886-62314874a365.png)

## It should look like:
** description of ideal **
It would be nice if it also works with remote connections.

**Comment by jeff-hykin** [comment]
With remote connections, you have to install the extension again (for all extensions including themes). I believe installing it "again" is actually just installing it on the remote system.

Let me know if this doesn't solve your issue, or I misunderstood something and I'll reopen it. Technically this should probably be solved by the remote code extension instead of on this repo.

**Comment by RohitRanjangit** [comment]
But there is no option for installing on wsl. It gets installed locally, I also tried some snippets to force   enable for remote connection but got same result no proper highlighting.

**Comment by RohitRanjangit** [comment]
I'm not able to install this extension on WSl. I'm attaching a screenshot of it.
![Screenshot (1)](https://user-images.githubusercontent.com/47271616/86947887-0b63b780-c16a-11ea-9288-1a3877e746be.png)
