### ISSUE TITLE
Bug in lookbehinds

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#93]
One line 582 you have
```ruby
when 'lookBehindFor'     then new_regex = /#{self_as_string}(?<=#{other_regex_as_string})/
when 'lookBehindToAvoid' then new_regex = /#{self_as_string}(?<!#{other_regex_as_string})/
```
when used as `/foo/.lookBehindFor(/bar/)` it creates the regular expression `/foo(?<=bar)/`
Ruby regular exprsssions don't support having the lookbehind after the matching expression
https://rubular.com/r/jtp9jWNG1R0BQE

**Comment by jeff-hykin** [comment]
Actually it is looking behind, but it's looking at `foo` because that's what's behind it haha. 

This case seems kinda dumb but you can use it like this
`/\d\d\d/.lookBehindFor(/777/)`
https://rubular.com/r/4GNRp7MyVeOaum

A more realistic use case if for exclusion.
`/\d\d\d/.lookBehindToAvoid(/666/)`
https://rubular.com/r/QN2EIBoKWobnz8
It will match all the digits except special cases
